version: "3.7"

services:
  db:
    environment:
      - POSTGRES_USER=woofr
      - POSTGRES_PASSWORD=woofr
      - POSTGRES_DB=woofr_db
    image: postgres:latest
    networks:
      - woofr
    ports:
      - 5405:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    image: quirosfelipe/woofr
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://woofr:woofr@db/woofr_db
      - PORT=5000
    networks:
      - woofr
    ports:
      - 8080:5000

networks:
  woofr:

volumes:
  postgres-data:
